# Generated by Django 4.2.4 on 2025-03-01 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 19, 9, 4, 667320, tzinfo=datetime.timezone.utc)),
        ),
    ]
