# Generated by Django 4.2.4 on 2025-03-07 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_status_status_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='background_color',
            field=models.CharField(default='#e8f4ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 16, 17, 6, 771266, tzinfo=datetime.timezone.utc)),
        ),
    ]
