# Generated by Django 4.2.4 on 2025-03-07 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_status_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('psychiatry', 'Psychiatry'), ('dental', 'Dental'), ('cardiology', 'Cardiology'), ('family Medicine', 'Family Medicine'), ('oncology', 'Oncology'), ('geriatrics', 'Geriatrics'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('general Medicine', 'General Medicine'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics')], default='Pediatrics', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 17, 20, 50, 585662, tzinfo=datetime.timezone.utc)),
        ),
    ]
