# Generated by Django 4.2.4 on 2025-04-20 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chatmessage_options_chatmessage_sender_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 19, 54, 53, 973129, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('doctor', 'patient')},
        ),
    ]
