# Generated by Django 4.2.4 on 2025-04-21 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_consultation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 12, 48, 41, 568025, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together={('doctor', 'patient')},
        ),
    ]
