# Generated by Django 4.2.4 on 2025-04-21 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_status_status_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 0, 22, 401167, tzinfo=datetime.timezone.utc)),
        ),
    ]
