# Generated by Django 4.2.4 on 2025-04-21 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_status_status_expires_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 4, 11, 81591, tzinfo=datetime.timezone.utc)),
        ),
    ]
