# Generated by Django 4.2.4 on 2025-04-21 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_consultation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 5, 34, 775445, tzinfo=datetime.timezone.utc)),
        ),
    ]
