# Generated by Django 4.2.4 on 2025-04-21 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_status_status_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 13, 27, 97367, tzinfo=datetime.timezone.utc)),
        ),
    ]
