# Generated by Django 4.2.4 on 2025-04-21 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_consultation_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 31, 28, 552480, tzinfo=datetime.timezone.utc)),
        ),
    ]
